version: '3.5'
services:
  frontend:
    container_name: bangarang-frontend
    build:
      context: ./app/client
    volumes:
      - './app/client:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development